version: '3.9'
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: TaskManagerServiceASP/Dockerfile
    depends_on:
      - mssql
    ports:
      - "8080:8080"
      - "8081:8081"
  
  mssql:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
